name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  BUILD_PATH: "."

jobs:
  lint:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: remove snap
        uses: ading2210/gh-actions-remove-snap@v1
      - uses: actions/checkout@v4
      
      - name: Cache Bun modules
        uses: actions/cache@v3
        with:
          path: ~/.bun/deps # or the actual bun cache directory, verify below
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
            
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install
        working-directory: ${{ env.BUILD_PATH }}

      - name: Check
        run: bun run check
        working-directory: ${{ env.BUILD_PATH }}
        
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  build:
    name: Build
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies with Bun
        run: bun install
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build with Astro
        run: |
          bun run build
        working-directory: ${{ env.BUILD_PATH }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  dockerci:
    name: Docker CI
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/coding4hours/bromine:$IMAGE_TAG


      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/coding4hours/bromine:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "coding4Hours"
          password: ${{ secrets.TOKEN }}

      - name: Push Docker container
        run: docker push ghcr.io/coding4hours/bromine:$IMAGE_TAG

  deploy:
    name: Deploy to GitHub Pages
    needs: [lint, build]
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: false
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

