name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  BUILD_PATH: "."

jobs:
  lint:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: remove snap
        uses: ading2210/gh-actions-remove-snap@v1
      - uses: actions/checkout@v4
      
      - name: Cache Bun modules
        uses: actions/cache@v3
        with:
          path: ~/.bun/deps
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
            
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install
        working-directory: ${{ env.BUILD_PATH }}

      - name: Check
        run: bun run check
        working-directory: ${{ env.BUILD_PATH }}
        
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          
  sync_to_lite:
    name: Sync to Bromine Lite
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean subdirectories (keep only required files)
        run: |
          shopt -s extglob

            \( -path "src/components/Footer.astro" \
            -o -path "src/gmes.json" \
            -o -path "src/gmes.astro" \
            -o -path "src/utils/gmes.ts" \
            -o -path "src/layouts/Layout.astro" \) -delete

          find src -type d -empty -delete

          rm -rf public/*

          set -euo pipefail
          
          if [ $# -lt 1 ]; then
            echo "Usage: $0 file1 [file2 ...]"
            exit 1
          fi
          
          for file in "$@"; do
            if [ ! -f "$file" ]; then
              echo "skip: $file (not a file)"
              continue
            fi
          
            # Create a backup
            cp -- "$file" "$file.bak"
            echo "backup: $file.bak"
          
            # Do transformations:
            # 1) remove import Lethal ...; lines (handles different quote styles and paths)
            # 2) remove <script>...</script> blocks that mention ./utils/lethal or currentFrame
            # 3) remove lines containing the JSX tag <Lethal />
            # 4) remove any lines that reference currentFrame.
            #
            # We use perl with dot-all mode for block removals, then sed for line removals.
            tmp="$(mktemp)"
          
            perl -0777 -pe '
              # 1) remove import Lethal ...;
              s{^\s*import\s+Lethal\b[^;]*;\s*}{}mg;
          
              # 2) remove any <script>...</script> block that mentions ./utils/lethal or currentFrame
              s{<script\b[^>]*>.*?(?:\./utils/lethal|currentFrame).*?<\/script>\s*}{}isg;
            ' -- "$file" \
            | sed -E '/\<Lethal[[:space:]]*\/\>/d' \
            | sed '/currentFrame\./d' \
            > "$tmp"
          
            mv "$tmp" "$file"
            echo "processed: $file"
          done


          echo "Lite cleanup complete."

      - name: Clone target repo
        run: |
          git clone https://github.com/Bromine-Labs/BromineLite.git target-repo
        env:
          GIT_TERMINAL_PROMPT: 0

      - name: Copy updated content
        run: |
          rsync -av --delete --exclude '.git' --exclude '.github' ./ target-repo/

      - name: Commit and push changes
        run: |
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Sync from source repo (Lite version)"
            git push origin main
          fi
        env:
          GIT_TERMINAL_PROMPT: 0
          GITHUB_TOKEN: ${{ secrets.TOKEN }}


  build:
    name: Build
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies with Bun
        run: bun install
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build with Astro
        run: bun run build
        working-directory: ${{ env.BUILD_PATH }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  dockerci:
    name: Docker CI
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Build Docker image (timestamped)
        run: docker build . --file Dockerfile --tag ghcr.io/coding4hours/bromine:$IMAGE_TAG

      - name: Build Docker image (latest)
        run: docker build . --file Dockerfile --tag ghcr.io/coding4hours/bromine:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "coding4Hours"
          password: ${{ secrets.TOKEN }}

      - name: Push Docker container (timestamped)
        run: docker push ghcr.io/coding4hours/bromine:$IMAGE_TAG
        
      - name: Push Docker container (latest)
        run: docker push ghcr.io/coding4hours/bromine:latest



  deploy:
    name: Deploy to GitHub Pages
    needs: [lint, build, sync_to_other_repo]
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: false
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
