name: Lighthouse

on:
  check_run:
    types: [completed]

jobs:
  audit:
    if: |
      github.event.check_run.name == 'pages-build-deployment' || 
      github.event.check_run.name == 'Cloudflare Pages'
    runs-on: ubuntu-latest

    steps:
      - name: remove snap
        uses: ading2210/gh-actions-remove-snap@v1
      - uses: actions/checkout@v4

      - name: Audit URLs using Lighthouse
        id: LHCIAction
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://bromine.pages.dev/
          runs: 10
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Send Lighthouse Links to Discord via Embed
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.ACTIONS_WEBHOOK_URL }}
          RAW_LINKS_OUTPUT: ${{ steps.LHCIAction.outputs.links }}
        run: |
          FORMATTED_DESCRIPTION=$(echo "$RAW_LINKS_OUTPUT" | jq -r '
            [
              to_entries | . as $items | range(length) as $i |
              "\($i + 1). **\($items[$i].key)**\n   ↳ [View Lighthouse Report](\($items[$i].value))"
            ] | join("\n\n")
          ')

          TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%S.000Z)

          JSON_PAYLOAD=$(jq -n \
            --arg username "Lighthouse Bot" \
            --arg description "$FORMATTED_DESCRIPTION" \
            --arg timestamp "$TIMESTAMP" \
            '{
              "username": $username,
              "avatar_url": "https://raw.githubusercontent.com/GoogleChrome/lighthouse/main/assets/lighthouse-logo.png",
              "embeds": [
                {
                  "title": "✅ Lighthouse Scan Results",
                  "description": $description,
                  "color": 3447003,
                  "footer": {
                    "text": "Report generated by Lighthouse CI"
                  },
                  "timestamp": $timestamp
                }
              ]
            }')

          curl -X POST -H "Content-Type: application/json" \
               -d "$JSON_PAYLOAD" \
               "${DISCORD_WEBHOOK_URL}"
